[[SYMPHONY]]
arch = "aarch64"
git-tree-sha1 = "1651e31ed96ac99bd44bee3c0a7e6366c989aed8"
os = "macos"

    [[SYMPHONY.download]]
    sha256 = "2f2a44ed79a4dd3b4b80d540cad86d4719f9d1b5219f46b651e8aee2f0c4f438"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.aarch64-apple-darwin.tar.gz"
[[SYMPHONY]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "888d3fa251dd5dd46ef2484fb7e04278f6378ff6"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "c2f0ad8e2f9c6e3c4742a99106d386d32ef28d3ac58afe003fea242bb254765d"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.aarch64-linux-gnu-cxx03.tar.gz"
[[SYMPHONY]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0879149217765a32f50dc5f96c04fe95f8c95ad0"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "8e6b7790a2eec761712920a42bb37fc6c61dcaec14380c3737db6750cf970ba3"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.aarch64-linux-gnu-cxx11.tar.gz"
[[SYMPHONY]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7401ea94a45fee91f67f5851cac42bccbe3d7f1c"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "093dedb150e9ff8856131b63d8bb02691a0bb8b184277fb8ce2091b8d1aa70e1"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.aarch64-linux-musl-cxx03.tar.gz"
[[SYMPHONY]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "820b169fb487f7b997be62a8062806fc2107fcea"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "f2d231850a9c2d9f2534a500111fab0b92a75fb028c254c0fe35abc6b52b6aa8"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.aarch64-linux-musl-cxx11.tar.gz"
[[SYMPHONY]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a7f3357926857f41fa3171e85025ec7881f41ab"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "46293225ef32d43f95f66d01b2bdec3b0ac2ab79e677b9facdb9c281d31c92af"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SYMPHONY]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79a669b3408bd0656179d8c050f080b51ab070b7"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "1216717b1bcd4e45e0952bf72e1684438db652c717b59d39a654fab79d254730"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SYMPHONY]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e403ccffe9281a8fedc2b77c8e41fd20e6ac1c15"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "a03459863bd949b8e74bc59690bf41a0592e48cb3ecbae90047baf9a98322aa0"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SYMPHONY]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d691b27a9f46500776b2f75a85dd95abd21c56d"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "e2e763e58915b8b6b9b8faaa99f1303b22ca0011322504b32793ea0f8482e2a8"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SYMPHONY]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c34bb785e55e5266a981a34df054dcfda97fed15"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "f0e8835b365ee72e04159f98971f0f1cb316e8bec5ced9ffc7070b04f02b48a3"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SYMPHONY]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32284193c10be44ee0a49a0a9f5fbb00a42f9784"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "5f0127271b28b419bc8a1cb36cf3f7e65fde904908107e5b3549657c019eaf40"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SYMPHONY]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d0ad8c1eaed6dc924b8e9b87e54ea8c44f2ad1e"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "6480ed728cc820c6a2d2b31d46f06e62036bf5c71388f53dbc6735f412522cfb"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SYMPHONY]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "906a7af17f5d63d031a2ac856f0251e7f9200b8a"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "184234de96999816d2bede2785324ad2d1eb3bfead20f5038856bd4939664321"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SYMPHONY]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4594fec936bb106f512c68358a013bcbb74a94ef"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "11f1cdcdf30df4c4698fb5744a8c2ebefc01f10e71d1592a61d34af5baf13456"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.i686-linux-gnu-cxx03.tar.gz"
[[SYMPHONY]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a71ba3fc086c7153394009feb523feff5b472baf"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "e915947a4d8447e2f686c718f3820de4334c40d33046b951411adc0683844afd"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.i686-linux-gnu-cxx11.tar.gz"
[[SYMPHONY]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fbbd27176796226664b4aaf1527fc6a71eb8e76"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "e568cbf0232c791f30d5ce6fb257ecbc5890203f3ca7a0cac232a0aa71a96105"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.i686-linux-musl-cxx03.tar.gz"
[[SYMPHONY]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1283ac3bac0170f0fc77810651e3263cbc55cde3"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "324db2543f32768d19c795a432a4e40af98b987c7d8497332f8f60d051e59bde"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.i686-linux-musl-cxx11.tar.gz"
[[SYMPHONY]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49399235a9f190e7abdf520c808b9d23268fd141"
os = "windows"

    [[SYMPHONY.download]]
    sha256 = "f5f8a08e3dbb5054e3bb079acfc4f1175c43369fea777e961d910e3dfb0bd65d"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.i686-w64-mingw32-cxx03.tar.gz"
[[SYMPHONY]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c17e13923434e5b91d687145a45746b2bb31e8a0"
os = "windows"

    [[SYMPHONY.download]]
    sha256 = "903430c7e9935ceb8130bd2a5f99790cab907eb066cf1f9a01b1b6b8f24332e6"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.i686-w64-mingw32-cxx11.tar.gz"
[[SYMPHONY]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df016d2b2637bd666cf27d03f7394a03bc9a9c12"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "2b0c0d8aaa19ed28579b8f7d54cd7dc466dc30b7f96f6c5591389b19286fd5bf"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SYMPHONY]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48b7828e46b927cc12ce49bde48fc88496d4ab41"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "ca9bf8fb1a8a8f9b65f0234d70f14ad22c420595d71b6e1bb0e36be80755b544"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SYMPHONY]]
arch = "x86_64"
git-tree-sha1 = "c2b5a420b44692131ee100f96cd283b2e14e3e9c"
os = "macos"

    [[SYMPHONY.download]]
    sha256 = "92917d9b157be9e1ed33817b081c57cbc6160883332ba8441961badf79bdef2d"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.x86_64-apple-darwin.tar.gz"
[[SYMPHONY]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfb00aff388b2f9b1b777b9e870c33341013a280"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "319ae06b94e5ad26b5a618054fcda201a87e529e5a31c6b0a16d4d0ba8289317"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.x86_64-linux-gnu-cxx03.tar.gz"
[[SYMPHONY]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e342517f34fc21fe5a8ce57f38d64433ddc56464"
libc = "glibc"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "f61dcdaec9a450c20409b73eb6725602a4613601a8489c862fa5907a15a65506"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.x86_64-linux-gnu-cxx11.tar.gz"
[[SYMPHONY]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6de9aae85825dd6491cc85b9de8f6046bca3602"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "e321b2ef0760393fb92b2b06c6b1f9ab9cf01880f5ceb1fe0c7cae6b4accd71c"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.x86_64-linux-musl-cxx03.tar.gz"
[[SYMPHONY]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc6debba670e5ec8d6aa4921f4385d0a937fbb93"
libc = "musl"
os = "linux"

    [[SYMPHONY.download]]
    sha256 = "b40737f134917486643da884ed442cb17d4d22fb17df959bd375dd55a575dd57"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.x86_64-linux-musl-cxx11.tar.gz"
[[SYMPHONY]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f653df23232ed47fcc8b7df46a4f1134f885805"
os = "windows"

    [[SYMPHONY.download]]
    sha256 = "72a334c255214578b072325aa9ba0a84ce7b0c2dd7d2da9c0ad72d25689e322e"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.x86_64-w64-mingw32-cxx03.tar.gz"
[[SYMPHONY]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "474f48d903ae5cce2e5823a8d34215ff31134311"
os = "windows"

    [[SYMPHONY.download]]
    sha256 = "c39b8d33ecdc859ac724205d9637672a2126d55c64b02ac46e35cd53733f262b"
    url = "https://github.com/JuliaBinaryWrappers/SYMPHONY_jll.jl/releases/download/SYMPHONY-v500.700.300+0/SYMPHONY.v500.700.300.x86_64-w64-mingw32-cxx11.tar.gz"
