# Autogenerated wrapper script for SYMPHONY_jll for x86_64-apple-darwin-libgfortran3
export libosisym, libsym, symphony

using CoinUtils_jll
using Osi_jll
using Clp_jll
using Cgl_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("SYMPHONY")
JLLWrappers.@declare_library_product(libosisym, "@rpath/libOsiSym.3.dylib")
JLLWrappers.@declare_library_product(libsym, "@rpath/libSym.3.dylib")
JLLWrappers.@declare_executable_product(symphony)
function __init__()
    JLLWrappers.@generate_init_header(CoinUtils_jll, Osi_jll, Clp_jll, Cgl_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libosisym,
        "lib/libOsiSym.3.6.19.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsym,
        "lib/libSym.3.6.19.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        symphony,
        "bin/symphony",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
